# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdc0f8b49b30e23e1e35202ed5125028a2d8a80a399c20ce51e87b47564a2af11cf2dba65ed074201f5379d54ae175304650d0d6fb777e62a638bf64904bd2c3

test:
  secret_key_base: 19554c1461d03571ba516329d987ce1d2a61df8aaea46cc764b7fa572248c12604d572bf7e0cbc1c14602f90400abd73e1d55019e8b10058ab0de6203719179c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
